# baseURL = 'https://jorisvandijk.com'
baseURL = '/'
languageCode = 'en-us'
title = 'Jorisvandijk.com'
theme = 'PaperMod'

# PaperMod configuration
[params]
  ShowSearchPage = true
  ShowCodeCopyButtons = true
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowToc = true

  # Favicon configuration
  [params.assets]
    favicon = "https://jorisvandijk.com/favicon.ico"
    favicon16x16 = "https://jorisvandijk.com/favicon-16x16.png"
    favicon32x32 = "https://jorisvandijk.com/favicon-32x32.png"
    apple_touch_icon = "https://jorisvandijk.com/apple-touch-icon.png"
  
  # Custom CSS will be automatically included
  # assets.customCSS = ['css/custom.css']

  [params.homeInfoParams]
  Title = "echo ${core_dump} > /www/blog"
  Content = "Linux mishaps, things that actually worked, half-baked ideas, and whatever else seemed worth jotting down when I should have been doing something more productive. I'm Joris, this is my blog. Hi."

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/jorisvandijk"

  [[params.socialIcons]]
  name = "gitlab"
  url = "https://gitlab.com/jorisvandijk"

  [[params.socialIcons]]
  name = "codeberg"
  url = "https://codeberg.org/jorisvandijk"

  [[params.socialIcons]]
  name = "rss"
  url = "index.xml"
  
# Pagination
paginate = 10
paginatePath = "page"

# Menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 30

[taxonomies]
  tag = "tags"
  
# Enable search index
[outputs]
  home = ["HTML", "RSS", "JSON"]

# Styling of codeblocks
[markup]
  [markup.highlight]
    lineNos = true
    codeFences = true
    guessSyntax = true
    noClasses = false 
