baseURL = 'https://jorisvandijk.github.io/website'
languageCode = 'en-us'
title = 'Jorisvandijk.com'
theme = 'PaperMod'

# PaperMod configuration
[params]
  ShowSearchPage = true
  ShowCodeCopyButtons = true
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowToc = true
  
  # Custom CSS will be automatically included
  # assets.customCSS = ['css/custom.css']

  [params.homeInfoParams]
  Title = "Welcome"
  Content = "Can be Info, links, about..."

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/jorisvandijk"

  [[params.socialIcons]]
  name = "gitlab"
  url = "https://gitlab.com/jorisvandijk"

  [[params.socialIcons]]
  name = "codeberg"
  url = "https://codeberg.org/jorisvandijk"

  [[params.socialIcons]]
  name = "rss"
  url = "index.xml"
  
# Pagination
paginate = 10
paginatePath = "page"

# Menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 30

[taxonomies]
  tag = "tags"
  
# Enable search index
[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    style = "github"
    lineNos = true
    codeFences = true
    guessSyntax = true
    noClasses = true
